In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset.head

<bound method NDFrame.head of            age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent
..         ...        ... ..  ...  ...     ...       ...         ...
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no
..          ...         ...  ...        ...           ...       ...  ...  ...
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no

     cad  appet    pe  ane classification
0     no    yes   yes   no            yes
1     no    yes  poor   no            yes
2     no    yes  poor   no            yes
3     no    yes  poor  yes            yes
4     no    yes  poor   no            yes
..   ...    ...   ...  ...            ...
394   no    yes  poor   no            yes
395   no    yes  poor  yes            yes
396   no   poor  poor   no            yes
397   no    yes  poor  yes            yes
398   no    yes  poor   no             no

[399 rows x 25 columns]>

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [6]:
dataset.head

<bound method NDFrame.head of            age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000
..         ...        ...  ...  ...         ...         ...       ...
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...      False        False       False
1    137.528754  4.627244  10.700000  ...       True        False       False
2    138.000000  4.400000  12.000000  ...       True        False       False
3    138.000000  3.200000   8.100000  ...       True        False       False
4    137.528754  4.627244  11.800000  ...       True        False       False
..          ...       ...        ...  ...        ...          ...         ...
394  139.000000  3.700000  12.500000  ...       True        False       False
395  137.528754  4.627244   8.700000  ...       True        False       False
396  134.000000  2.700000   9.100000  ...       True        False       False
397  142.000000  5.500000   8.500000  ...       True        False       False
398  140.000000  5.000000  16.300000  ...       True        False       False

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes
0      False   False    False       True    True    False                True
1      False   False    False       True   False    False                True
2      False   False    False       True   False    False                True
3      False   False    False       True   False     True                True
4      False   False    False       True   False    False                True
..       ...     ...      ...        ...     ...      ...                 ...
394    False   False    False       True   False    False                True
395     True    True    False       True   False     True                True
396     True    True    False      False   False    False                True
397     True    True    False       True   False     True                True
398    False   False    False       True   False    False               False

[399 rows x 28 columns]>

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
cols_to_fix=['sg_b', 'sg_c', 'sg_d', 'sg_e','rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes','classification_yes']
dataset[cols_to_fix]=dataset[cols_to_fix].astype(int)
dataset[cols_to_fix]

,sg_b,sg_c,sg_d,sg_e,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,0,1,0,0,1,0,0,0,0,0,0,1,1,0,1
1,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1
2,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1
3,0,0,1,0,1,1,0,0,0,0,0,1,0,1,1
4,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1
395,0,1,0,0,1,1,0,0,1,1,0,1,0,1,1
396,0,1,0,0,1,1,0,0,1,1,0,0,0,0,1
397,0,0,0,0,1,1,0,0,1,1,0,1,0,1,1
398,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0

In [9]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [10]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
from sklearn.svm import SVC

In [14]:
from sklearn.model_selection import GridSearchCV

param_grid = {'kernel':['linear','rbf','poly','sigmoid'],
             'gamma':['auto','scale'],
             'C':[10,100,1000,2000,3000]} 



grid = GridSearchCV(SVC(probability=True),param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [15]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [16]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}: 0.9924946382275899

In [17]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [18]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [19]:
from sklearn.metrics import roc_auc_score


roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

np.float64(1.0)

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.022483,0.002605,0.021375,0.001824,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
1,0.023037,0.003034,0.021416,0.003629,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,1.000000,1.000000,0.988859,0.014751,4
2,0.031421,0.005159,0.019562,0.003369,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",1.000000,0.981014,1.000000,1.000000,0.981217,0.992446,0.009252,3
3,0.020972,0.005204,0.023392,0.004265,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.981569,1.000000,1.000000,0.981031,1.000000,0.992520,0.009163,1
4,0.018079,0.005023,0.017978,0.003766,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
5,0.015369,0.002836,0.016691,0.001625,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,1.000000,1.000000,0.988859,0.014751,4
6,0.027053,0.004875,0.017071,0.002098,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",1.000000,0.981014,1.000000,0.981031,0.981217,0.988652,0.009266,6
7,0.017121,0.001306,0.016572,0.001461,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.981569,1.000000,1.000000,0.981031,1.000000,0.992520,0.009163,1
8,0.010599,0.001997,0.016066,0.000754,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
9,0.010352,0.000396,0.016092,0.001340,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,9
10,0.019910,0.001648,0.016179,0.000926,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.963284,0.981014,1.000000,1.000000,0.981217,0.985103,0.013797,7
11,0.011785,0.000763,0.015397,0.000774,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.981569,0.943699,0.944023,0.981031,1.000000,0.970065,0.022459,33
12,0.013753,0.002281,0.016359,0.000698,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
13,0.011672,0.001334,0.015142,0.000395,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,9
14,0.021112,0.001800,0.017815,0.003070,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.963284,0.981014,1.000000,1.000000,0.981217,0.985103,0.013797,7
15,0.015530,0.003053,0.016905,0.002078,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.981569,0.943699,0.944023,0.981031,1.000000,0.970065,0.022459,33
16,0.011634,0.001305,0.015353,0.000242,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
17,0.012672,0.002266,0.015222,0.000578,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,9
18,0.021221,0.003589,0.015481,0.001055,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,17
19,0.012045,0.002338,0.015384,0.001410,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,35
20,0.011992,0.001382,0.015035,0.000296,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
21,0.011890,0.001721,0.015526,0.001112,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,9
22,0.021563,0.002742,0.015885,0.000803,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,17
23,0.014021,0.005571,0.015892,0.001274,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,35
24,0.012850,0.000962,0.015338,0.000643,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
25,0.013941,0.002634,0.014983,0.000971,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,9
26,0.019624,0.001852,0.016500,0.001265,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,17
27,0.012281,0.000871,0.015974,0.001199,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,35
28,0.011802,0.002547,0.015803,0.000827,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
29,0.013226,0.002650,0.015652,0.000870,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,9
30,0.022371,0.002800,0.015508,0.000477,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,17
31,0.011677,0.001369,0.015873,0.001340,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,35
32,0.011661,0.001533,0.017223,0.001552,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
33,0.013584,0.001296,0.017106,0.001780,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,9
34,0.019495,0.002660,0.017066,0.002449,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,17
35,0.014126,0.002844,0.015592,0.000441,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,35
36,0.013899,0.003906,0.017011,0.000522,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,23
37,0.014250,0.002531,0.015315,0.000618,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,9
38,0.020451,0.001969,0.015260,0.000254,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,17
39,0.010647,0.001471,0.014953,0.000358,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,35